Add CodecContext to allow getting the session inside of a Codec
GlowstonePlusPlus/network pull request #1
Opened 2018-10-05 19:54 UTC by jdonkervliet

Cherry-picked commit from @Paulomart: https://github.com/Paulomart/network/commit/bd32ed91b8b2b78360490c98ecd10f5ff73dcd56

2018-10-06 04:45 UTC, aramperes requested changes

2018-10-06 04:45 UTC, momothereal commented on src/main/java/com/flowpowered/network/pipeline/MessageDecoder.java
> +    	if (context == null && messageHandler.getSession() != null) {
Replace the tab with spaces

2018-10-06 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/network?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/network?pullRequest=1) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Paulomart<br/>:x: Jesse Donkervliet<br/><hr/>**Jesse Donkervliet** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/network?pullRequest=1) it.</sub>

2018-10-07 00:42 UTC, aramperes approved these changes

2018-10-07 00:43 UTC, momothereal commented
Could you bump the library's version to `1.2.5-SNAPSHOT`?

2018-10-07 12:20 UTC, jdonkervliet commented
Actually, I want to create a release for this repo. Can we first get to 1.2.4 before continuing with 1.2.5?

2018-10-07 13:38 UTC, merged

2018-10-07 13:38 UTC, momothereal commented
Thanks for your contribution! I released 1.2.4 and started the 1.2.5 snapshots before merging this. This commit will be part of the 1.2.5 release.

2018-11-05 01:18 UTC, c-edw commented
We've discussed reverting this over [here](https://github.com/GlowstoneMC/Glowstone/pull/972). I think it might be a good idea to find out why this was implemented before reverting it. We should also consider that reverting it will diverge further from upstream `flow/network`.