Upadated README.md; Hacktoberfest-2018
GlowstonePlusPlus/network pull request #3
Opened 2018-10-07 16:06 UTC by preeti98

Please do let me know if I need to make any further specific changes. Thank you!
This is a PR in response to issue #2

2018-10-07 16:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/GlowstoneMC/network?pullRequest=3) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/GlowstoneMC/network?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/GlowstoneMC/network?pullRequest=3) it.</sub>

2018-10-07 17:28 UTC, aramperes requested changes
Thanks for working on this! I submitted a few more changes we'd like to see. Please make sure you also sign the CLA.

2018-10-07 17:28 UTC, momothereal commented on README.md
> +# Flow Network [![License](http://img.shields.io/badge/license-MIT-lightgrey.svg?style=flat)][License] [![Flattr this](http://img.shields.io/badge/flattr-donate-lightgrey.svg?style=flat)][Donate] [![
Remove the `[![Flattr this](http://img.shields.io/badge/flattr-donate-lightgrey.svg?style=flat)][Donate]` (donate shield)

2018-10-07 17:28 UTC, momothereal commented on README.md
> +Love the project? Feel free to donate to help continue development! Flow projects are open-source and powered by community members, like yourself. Without you, we wouldn't be here today!
You can remove this line altogether. The Glowstone project doesn't accept donations at the moment.

2018-10-07 17:28 UTC, momothereal commented on README.md
> +        <url>https://repo.glowstone.net/content/repositories/snapshots/</url>
I made a mistake here, the URL should be `https://repo.glowstone.net/content/repositories/releases/`

2018-10-07 17:28 UTC, momothereal commented on README.md
>  If you plan on using snapshots and do not already have the snapshot repo in your repository list, you will need to add this as well:
Remove this paragraph, including the line about manually importing the JAR.

2018-10-07 17:28 UTC, momothereal commented on README.md
> +Feel free to contact us on [discord](https://discord.gg/TFJqhsC)
`Discord` (with a capital D)

2018-10-07 17:28 UTC, momothereal commented on README.md
> +If you're using Maven Project to manage project dependencies, simply include the following in your `pom.xml` file:
Change this line to

> You will also need to add the Glowstone Maven repository in your `pom.xml` file:

2018-10-07 19:22 UTC, preeti98 commented
Please do let me know if further changes are required!

2018-10-09 14:12 UTC, mastercoms commented
@momothereal Are there any more changes needed?

2018-10-09 20:58 UTC, aramperes approved these changes

2018-10-09 20:58 UTC, merged